spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8072