spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    key-values:
      application: ${spring.application.name}

server:
  port: 8072

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"