spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers:
      - broker:29092

server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    prefer-ip-address: true


