version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    platform: linux/x86_64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1


  #  config-server:
#    image: kqinneh/config-server:v1
#    container_name: config-server
#    platform: linux/x86_64
#    ports:
#      - "8888:8888"
#    expose:
#      - "8888"
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#    networks:
#      - services


  store-service:
    image: kqinneh/store-service:v1
    container_name: store-service
    platform: linux/x86_64
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb_container
      - service-registry
    restart: always
    networks:
      - services

  review-service:
    image: kqinneh/review-service:v1
    container_name: review-service
    platform: linux/x86_64
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb_container
      - kafka
      - zookeeper
      - service-registry
    restart: always
    networks:
      - services

  service-registry:
    image: kqinneh/service-registry:v1
    container_name: service-registry
    platform: linux/x86_64
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=docker
    restart: always
    networks:
      - services

  notification-service:
    image: kqinneh/notification-service:v1
    container_name: notification-service
    platform: linux/x86_64
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb_container
      - kafka
      - zookeeper
      - service-registry
    restart: always
    networks:
      - services

  gateway-server:
    image: kqinneh/gateway-server:v1
    container_name: gateway-server
    platform: linux/x86_64
    expose:
      - "8072"
        #    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - store-service
      - review-service
      - notification-service
      - service-registry
    restart: always
    networks:
      - services

networks:
  kafka-net:
    driver: bridge
  services:
    driver: bridge
volumes:
  mongodb_data_container: