global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'notification-service'
    metrics_path: 'notification-service/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]


  - job_name: 'review-service'
    metrics_path: 'review-service/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]


  - job_name: 'store-service'
    metrics_path: 'store-service/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]


  - job_name: 'service-registry'
    metrics_path: 'service-registry/actuator/prometheus'
    static_configs:
      - targets: [ 'gateway-server:8072' ]



