spring:
  cloud:
    config:
#      token: myroot
      discovery:
        enabled: true
      server:
        git:
          uri: ${CONFIG_REPO:https://github.com/karamalqinneh/ecommerce-microservices-config }
          default-label: main

  application:
    name: config-server

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    key-values:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"