spring:
  application:
    name: review-service

server:
  port: 0


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true

resilience4j:
  circuit-breaker:
    instances:
      reviewService:
        event-consumer-buffer-size: 10
        registerHealthIndicator: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 60
        permittedNumberOfCallsInHalfOpenState: 3

app:
  secret: karam is the owner + this is added on runtime + now removed on runtime

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    key-values:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"