spring:
  application:
    name: review-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: review-main


server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true