spring:
  application:
    name: store-service
  logging:
    level:
      org.springframework.kafka: DEBUG
  data:
    mongodb:
      host: localhost
      port: 27017
      database: store-main
    kafka:
      bootstrap-servers:
        - ${KAFKA_URL:broker:29092 }

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  observations:
    key-values:
      application: ${spring.application.name}